top_srcdir   = /home/parallels/src/httpd-2.2.22
top_builddir = /home/parallels/src/httpd-2.2.22
srcdir       = /home/parallels/src/httpd-2.2.22/os
builddir     = /home/parallels/src/httpd-2.2.22/os
VPATH        = /home/parallels/src/httpd-2.2.22/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
