top_srcdir   = /home/parallels/src/httpd-2.2.22
top_builddir = /home/parallels/src/httpd-2.2.22
srcdir       = /home/parallels/src/httpd-2.2.22/modules/dav/lock
builddir     = /home/parallels/src/httpd-2.2.22/modules/dav/lock
VPATH        = /home/parallels/src/httpd-2.2.22/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
