top_srcdir   = /home/parallels/src/httpd-2.2.22
top_builddir = /home/parallels/src/httpd-2.2.22
srcdir       = /home/parallels/src/httpd-2.2.22/modules/http
builddir     = /home/parallels/src/httpd-2.2.22/modules/http
VPATH        = /home/parallels/src/httpd-2.2.22/modules/http

include $(top_srcdir)/build/special.mk

