top_srcdir   = /home/parallels/src/httpd-2.2.22
top_builddir = /home/parallels/src/httpd-2.2.22
srcdir       = /home/parallels/src/httpd-2.2.22/modules/loggers
builddir     = /home/parallels/src/httpd-2.2.22/modules/loggers
VPATH        = /home/parallels/src/httpd-2.2.22/modules/loggers

include $(top_srcdir)/build/special.mk

